### ISSUE TITLE
PR process

### ISSUE THREAD

**Issue by skylize** [littleball-games/lb-f#11]
I think you should consider adding me as a member on the repo so you can set a requirement for a Review before merging changes.

**Comment by Eruant** [comment]
Initially I would like to get the project up and running with pieces in place. After that I will be adding members. I may change the project name (Poll running on [fun-fun-forum](https://www.patreon.com/funfunfunction/posts)).

**Comment by skylize** [comment]
Closing this as resolved as the Review To Merge is now in place. :+1:
