### ISSUE TITLE
Should flip only flip the first 2 arguments?

### ISSUE THREAD

**Issue by skylize** [littleball-games/lb-f#14]
### Summary of issue

Our current `flip` function reverses all arguments before calling the underlying function. The common implementation for `flip` is to flip only the first two arguments, probably because Haskell's `flip` only switches two arguments.

```hs
flip :: (a -> b -> c) -> b -> a -> c
```

Personally I like our current version, but at the moment I cannot come up with a good argument for why. It could cause confusion for people with preconceived expectations of how a `flip` should behave. 

Should we conform?

**Comment by skylize** [comment]
I've come up with one decent argument in favor of flipping all args. It has to do with legacy of javascript apis. A common case for `flip` in js would be to get the first argument last or the last argument first for a 3rd party function designed without currying in mind. This is a concern they would not need to deal with in Haskell.

**Comment by Eruant** [comment]
The current `flip` function does flip the first two arguments. It slices off the first two arguments (and therefore ignores all other arguments), and reverses them.

```javascript
fn(
  ...args.slice(0, fn.length).reverse()
)
```

**Comment by skylize** [comment]
@Eruant 
> The current flip function does flip the first two arguments.

That is correct if only 2 arguments are expected. But if calling a function with 10 arguments, then all 10 will be reversed at once by the current implementation, not just the first two.

**Comment by Eruant** [comment]
@skylize 
`fn.length` will be the number of aruments the function requires. So `...args(0, fn.length)` will be the number of arguments required for that function. We then reverse all of them.

```javascript
const add2 = (a, b) => a + b
const add3 = (a, b, c) => a + b + c

add2.length // 2
add3.length // 3
```

If we fliped `add2` can called it with 10 arguments, it will ignore the 8 arguments not required and flip the 2 that are required.

**Comment by skylize** [comment]
Correct. A function like `add` will behave as expected for everyone. The issue is when the flipped function expects more arguments. Compare the type signatures in the following example.

```js
import { flip } from 'lb-f'
import { flip as ramdaFlip } from 'ramda'

const myFnWithTooManyArgs = (a, b, c, d, e, f, g) => 'some value z'

// f1 :: g -> f -> e -> d -> c -> b -> a -> z
const f1 = flip(myFnWithTooManyArgs)

// f2 :: b -> a -> c -> d -> e -> f -> g -> z
const f2 = ramdaFlip(myFnWithTooManyArgs)

```

**Comment by Eruant** [comment]
I see where you are coming from now.
